update section welcome-main and add welcome-main-css
DmytroZhdanov/mimino pull request #32
Opened 2023-02-26 21:13 UTC by Tatsisli

Додала зміни в html  секції welcom-main, додаю стилі для цієї секції з медіаправилами. Не знаю, як знайти картинки через VSC

2023-02-26 22:30 UTC, DmytroZhdanov requested changes
Треба тільки прибрати клас .container звідусіль, бо він вже є у спільних і підправити картинку. А так, все супер!!

2023-02-26 22:30 UTC, DmytroZhdanov commented on src/css/layout/welcome-main.css
> +  }
Клас .container вже прописаний у спільних файлах. Звідси можна видалити

2023-02-26 22:30 UTC, DmytroZhdanov commented on src/partials/main/welcome-main.html
> +            ./img/main-welcome/main-welcome-3x-2112.webp 2112w
Додай ще ./img/main-welcome/main-welcome-3x-1005.webp 1005w,
Пропущена одна картинка.
І, я не знаю чи впливає це на браузер, але про всяк випадок, розташуй всі картинки в srcset по зростанню ширини, не зважаючі на ікси. Тобто просто поміняти місцями, зробити аби було 335, 670, 672, 704, 1005, 1344, 1408, 2016, 2112

2023-02-27 07:08 UTC, Tatsisli commented on src/css/layout/welcome-main.css
> +  }
Привіт, дякую. видалю.

2023-02-27 07:08 UTC, Tatsisli commented on src/partials/main/welcome-main.html
> +            ./img/main-welcome/main-welcome-3x-2112.webp 2112w
Дякую, все перероблю

2023-02-27 08:30 UTC, DmytroZhdanov approved these changes

2023-02-27 08:30 UTC, merged