Подивись на анімацію, скажи ,що думаєш
DmytroZhdanov/mimino pull request #84
Opened 2023-03-12 12:08 UTC by Anastasiia578

2023-03-12 17:58 UTC, DmytroZhdanov requested changes
Анімацію не зміг подивитись, бо ламається скрипт і нічого не спрацьовує

2023-03-12 17:58 UTC, DmytroZhdanov commented on src/partials/modals/book-a-table-modal.html
> +        <button data-modal-prices-close type="button" class="modal-close"><svg class="icon-clos" width="28" height="28">
Ось тут неправильний дата атрибут вказаний. Через це не спрацьовує скрипт. Має бути data-modal-table-close

2023-03-12 17:58 UTC, DmytroZhdanov commented on src/partials/modals/book-a-room-modal.html
> +                        <option class="option-style" value="double-suite">DOUBLE SUITE</option>
Я думаю краще залишити один double suit і дати йому атрибут selected. Бо якщо користувач не захоче змінювати тип кімнати, а залишити за замовчування, то на сервер прийде пусте значення. І плюс, якщо не помиляюсь, при відкриванні списку з варіантами, зараз буде двічі показувати цей double suit

2023-03-12 17:58 UTC, DmytroZhdanov commented on src/partials/modals/book-a-table-modal.html
> +<!-- Prices per Room Modal window -->
Це має бути модалка замовлення столику, а не кімнати)

2023-03-12 17:58 UTC, DmytroZhdanov commented on src/partials/modals/book-a-table-modal.html
> +<div class="backdrop is-hidden" data-modal-prices>
Столик, а не цінник))

2023-03-13 06:28 UTC, Anastasiia578 commented on src/partials/modals/book-a-table-modal.html
> +        <button data-modal-prices-close type="button" class="modal-close"><svg class="icon-clos" width="28" height="28">
Тут я ніфіга не робила, воно мені вже із змінами таке потрапило, але пофікшу, то таке

2023-03-13 06:29 UTC, Anastasiia578 commented on src/partials/modals/book-a-room-modal.html
> +                        <option class="option-style" value="double-suite">DOUBLE SUITE</option>
Тоді валідатор скаржиться, що це не семантично,а вилітає лише один дабл рум, бо у першого не вказана value

2023-03-13 06:31 UTC, Anastasiia578 commented on src/partials/modals/book-a-table-modal.html
> +<div class="backdrop is-hidden" data-modal-prices>
Еммм, шось пішло не так... я взагалі не пам'ятаю щоб там зміни вносила

2023-05-05 12:49 UTC, closed without merging