section done
DmytroZhdanov/mimino pull request #9
Opened 2023-02-24 18:53 UTC by DanilaCh01

2023-02-24 21:27 UTC, DmytroZhdanov requested changes
Хороша робота! Є декілька моментів, виправи, будь ласка)

2023-02-24 21:27 UTC, DmytroZhdanov commented on src/partials/hotel/four-seater-room-hotel.html
> +          Book now for a memorable stay.
Теґ br не потрібен. Просто задай ширину параграфу

2023-02-24 21:27 UTC, DmytroZhdanov commented on src/partials/hotel/four-seater-room-hotel.html
> +          <button class="room-four__button">More details</button>
Тут буде не кнопка, а посилання на сторінку Room

2023-02-24 21:27 UTC, DmytroZhdanov commented on src/css/pages/hotel/four-seater-room-hotel.css
> +.room-four {}
Тут падінги для секції скорішк за все винесуть в загальний файл, тому можеш видалити

2023-02-24 21:27 UTC, DmytroZhdanov commented on src/css/pages/hotel/four-seater-room-hotel.css
> +.image-collage__item {}
Пусте правило краще прибрати

2023-02-24 21:27 UTC, DmytroZhdanov commented on src/css/pages/hotel/four-seater-room-hotel.css
> +}
Це буде винесено в reset, тому теж видали

2023-02-24 21:27 UTC, DmytroZhdanov commented on src/css/pages/hotel/four-seater-room-hotel.css
> +}
Клопка також буде винесена в окремий файл, тому тут вона не потрібна

2023-02-25 20:11 UTC, DmytroZhdanov requested changes

2023-02-25 20:11 UTC, DmytroZhdanov commented on src/partials/hotel/four-seater-room-hotel.html
> +          <a class="room-four__button" href="#">More details</a>
Ось тут все вірно, посилання

2023-02-25 20:11 UTC, DmytroZhdanov commented on src/partials/hotel/four-seater-room-hotel.html
> +          <a class="room-four__button" href="#">View prices</a>
Ось тут треба було залишити кнопку, бо вона відкриває модалку

2023-02-25 20:11 UTC, DmytroZhdanov commented on src/css/pages/hotel/four-seater-room-hotel.css
>  }
Ось тут перевір, будь ласка, можливо мені не показує. Але можливо в тебе тут не має селектора з відкриваючою дужкою

2023-02-26 09:10 UTC, DanilaCh01 commented on src/css/pages/hotel/four-seater-room-hotel.css
>  }
![image](https://user-images.githubusercontent.com/117128628/221401745-1ef29fda-2e66-4ed0-879d-baba1f08cb65.png)
Перевірив, ось всі стилі. Не бачу щоб був невідкритий селектор.

2023-02-26 09:38 UTC, DmytroZhdanov commented on src/css/pages/hotel/four-seater-room-hotel.css
>  }
Прекрасно))

2023-02-26 10:40 UTC, DmytroZhdanov approved these changes

2023-02-26 10:40 UTC, merged